[package]
name = "rnim_lexer"
edition = "2021"
version = "0.1.0"
description = "Nim tokenization, indentation/offside handling, comments, numeric/string literal scanning"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
unicode-ident = { workspace = true }
smol_str = { workspace = true }
rnim_span = { path = "../rnim_span" }
thiserror = { workspace = true }
