[package]
name = "rnim_codegen_c"
edition = "2021"
version = "0.1.0"
description = "C/C++/Objective-C compatible backend, generated headers, ABI lowering, external compiler invocation"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[lints.rust]
unsafe_code = "allow"
dead_code = "warn"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
camino = { workspace = true }
rnim_span = { path = "../rnim_span" }
rnim_mir = { path = "../rnim_mir" }
