[package]
name = "rnim_lifetime"
edition = "2021"
version = "0.1.0"
description = "ARC/ORC lowering, move analysis, hook injection, sink/lent validation"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
petgraph = { workspace = true }
rnim_span = { path = "../rnim_span" }
rnim_hir = { path = "../rnim_hir" }
rnim_mir = { path = "../rnim_mir" }
