[package]
name = "rnim_query"
edition = "2021"
version = "0.1.0"
description = "Incremental compilation query database with salsa-style invalidation"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"
[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }
tempfile = { workspace = true }

[dependencies]
salsa = { workspace = true }
rustc-hash = { workspace = true }
rnim_span = { path = "../rnim_span" }
rnim_session = { path = "../rnim_session" }
