[package]
name = "rnim_docgen"
edition = "2021"
version = "0.1.0"
description = "Documentation generation from Nim modules, comments, exported symbols, and doc config"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
pulldown-cmark = "0.10"
rnim_span = { path = "../rnim_span" }
rnim_ast = { path = "../rnim_ast" }
