[package]
name = "rnim_diag"
edition = "2021"
version = "0.1.0"
description = "Error rendering, structured suggestions, machine-readable JSON diagnostics"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
ariadne = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rnim_span = { path = "../rnim_span" }
thiserror = { workspace = true }
