[package]
name = "rnim_types"
edition = "2021"
version = "0.1.0"
description = "Type representation, unification, conversions, concepts/type classes, generic instantiation"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
rnim_span = { path = "../rnim_span" }
rnim_ast = { path = "../rnim_ast" }
camino = "1.1"
fnv = "1.0"
