[package]
name = "rnim_test"
edition = "2021"
version = "0.1.0"
description = "Conformance test runner, golden tests, differential tests against official Nim when available"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
cargo_metadata = "0.18"
rnim_session = { path = "../rnim_session" }
rnim_parser = { path = "../rnim_parser" }
tempfile = { workspace = true }
