[package]
name = "rnim_symbols"
edition = "2021"
version = "0.1.0"
description = "Symbol interning, module graph, import/export visibility, overload sets"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
indexmap = { workspace = true }
rustc-hash = { workspace = true }
slotmap = { workspace = true }
rnim_span = { path = "../rnim_span" }
rnim_ast = { path = "../rnim_ast" }
