[package]
name = "chimera"
edition = "2021"
version = "0.1.0"
description = "Rust implementation of the Nim compiler"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[lints.rust]
unsafe_code = "deny"
dead_code = "warn"
unused_variables = "warn"
unused_imports = "warn"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
rnim_session = { path = "../rnim_session" }
rnim_lexer = { path = "../rnim_lexer" }
rnim_parser = { path = "../rnim_parser" }
rnim_ast = { path = "../rnim_ast" }
rnim_diag = { path = "../rnim_diag" }
rnim_codegen_c = { path = "../rnim_codegen_c" }
rnim_codegen_js = { path = "../rnim_codegen_js" }
rnim_docgen = { path = "../rnim_docgen" }
rnim_sema = { path = "../rnim_sema" }
rnim_suggest = { path = "../rnim_suggest" }
rnim_span = { path = "../rnim_span" }
camino = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
