[package]
name = "rnim_span"
edition = "2021"
version = "0.1.0"
description = "Source files, byte/line/column mapping, stable spans, hygiene contexts"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
codespan-reporting = { workspace = true }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
