[package]
name = "rnim_codegen_js"
edition = "2021"
version = "0.1.0"
description = "JavaScript backend for supported Nim JS compilation mode"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[lints.rust]
unsafe_code = "allow"
dead_code = "warn"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
rnim_span = { path = "../rnim_span" }
rnim_mir = { path = "../rnim_mir" }
camino = "1.1"
