[package]
name = "rnim_ast"
edition = "2021"
version = "0.1.0"
description = "Typed AST wrappers over lossless syntax tree plus AST validation helpers"
license = "0BSD"
repository = "https://github.com/chimera-nim/chimera-nim"

[dev-dependencies]
rnim_allocator = { path = "../rnim_allocator" }

[dependencies]
rowan = { workspace = true }
rnim_span = { path = "../rnim_span" }
rnim_parser = { path = "../rnim_parser" }
